export const userMock = {
  "login": "Deivid182",
  "id": 67056846,
  "node_id": "MDQ6VXNlcjY3MDU2ODQ2",
  "avatar_url": "https://avatars.githubusercontent.com/u/67056846?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Deivid182",
  "html_url": "https://github.com/Deivid182",
  "followers_url": "https://api.github.com/users/Deivid182/followers",
  "following_url": "https://api.github.com/users/Deivid182/following{/other_user}",
  "gists_url": "https://api.github.com/users/Deivid182/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Deivid182/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Deivid182/subscriptions",
  "organizations_url": "https://api.github.com/users/Deivid182/orgs",
  "repos_url": "https://api.github.com/users/Deivid182/repos",
  "events_url": "https://api.github.com/users/Deivid182/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Deivid182/received_events",
  "type": "User",
  "site_admin": false,
  "name": "davepm",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Front-end Developer",
  "twitter_username": "DaveDev5173",
  "public_repos": 85,
  "public_gists": 0,
  "followers": 2,
  "following": 21,
  "created_at": "2020-06-17T12:32:58Z",
  "updated_at": "2024-04-20T20:34:08Z"
}